markdown: kramdown
baseurl: "https://claudiomateluna.github.io/abv"
url: https://claudiomateluna.github.io/abv
exclude: ['README.md']
encoding: utf-8
titulo: ABV POS
permalink: pretty

collections:
  docs:
    output: true
